apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.stockdatasync.displayname }}
  namespace: {{ .Values.stockdatasync.displayname }}
  labels:
    application: {{ .Values.stockdatasync.displayname }}
    version: 0.0.1

spec:
  replicas: 1
  selector:
    matchLabels:
      application: {{ .Values.stockDataSync.displayname }}

  template:
    metadata:
      labels:
        application: {{ .Values.stockDataSync.displayname }}
    spec:
      serviceAccountName: {{ .Values.stockDataSync.serviceAccountName }}
      containers:
        - name: {{ .Values.stockDataSync.displayname }}
          image: "{{ .Values.stockDataSync.image.registry }}/{{ .Values.stockDataSync.image.name }}:{{ .Values.stockDataSync.image.version }}"
          imagePullPolicy: IfNotPresent
          command:
          - /bin/sh
          - -c
          - sleep 1000
          ports:
            - name: {{ .Values.stockDataSync.port.name }}
              containerPort: {{ .Values.stockDataSync.port.number }}
          livenessProbe:
            httpGet: 
              path: "/ping"
              port: {{ .Values.stockDataSync.port.number }}
            initialDelaySeconds: 10
            periodSeconds: 30
          env:
            - name: ALPHAVANTAGE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: data-source-secret
                  key: ALPHAVANTAGE_API_KEY

