apiVersion: apps/v1
kind: Deployment
metadata:
  name: stocks-data-sync
  namespace: stocks-data-sync
  labels:
    application: stocks-data-sync
    version: 0.0.1

spec:
  replicas: 1
  selector:
    matchLabels:
      application: stocks-data-sync

  template:
    metadata:
      labels:
        application: stocks-data-sync
    spec:
      serviceAccountName: stocks-data-sync-admin
      containers:
        - name: stocks-data-sync
          image: "docker.io/alejandropriv/data-sync:{{ .Values.stocksDataSync.version }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: port
              containerPort: 3080
          livenessProbe:
            exec:
              command: [ "python", "/app/probe.py" ]
            initialDelaySeconds: 20
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          env:
            - name: ALPHAVANTAGE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: stocks-data-sync
                  key: ALPHAVANTAGE_API_KEY

