apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-data-sync
  namespace: stock-data-sync
  labels:
    application: stock-data-sync
    version: 0.0.1

spec:
  replicas: 1
  selector:
    matchLabels:
      application: stock-data-sync

  template:
    metadata:
      labels:
        application: stock-data-sync
    spec:
      serviceAccountName: stock-data-sync-admin
      containers:
        - name: stock-data-sync
          image: "{{ .Values.stockDataSync.image.registry }}/{{ .Values.stockDataSync.image.name }}:{{ .Values.stockDataSync.image.version }}"
          imagePullPolicy: IfNotPresent
          command:
          - /bin/sh
          - -c
          - sleep 1000
          ports:
            - name: stock-data-sync-port
              containerPort: 3080
          livenessProbe:
            httpGet: 
              path: "/ping"
              port: 3080
            initialDelaySeconds: 10
            periodSeconds: 30
          env:
            - name: ALPHAVANTAGE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: data-source-secret
                  key: ALPHAVANTAGE_API_KEY

