apiVersion: v1
kind: ServiceAccount
metadata:
  name: stock-data-sync-admin
  namespace: stock-data-sync
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "001"
    "helm.sh/hook-delete-policy": before-hook-creation
