apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stock-data-sync
  namespace: argocd
spec:
    source:
      targetRevision: dev
      helm:
        valueFiles:
        - values/development/values.yaml
    syncPolicy:
      automated: { }
