apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stocks-data-sync
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/stocks-analyser/StockDataSync"
    path: deploy/helm
    helm:
      releaseName: stocks-data-sync
      #parameters:
      #  - name: StockDataSync.version
      #    value: $ARGOCD_APP_REVISION_SHORT
  destination:
    server: "https://kubernetes.default.svc"
    namespace: stocks-data-sync