apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stocks-data-sync
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/stocks-analyser/stocks-data-sync.git"
    path: deploy/helm
    helm:
      releaseName: stocks-data-sync
      parameters:
        - name: stocksDataSync.version
          value: $ARGOCD_APP_REVISION_SHORT
          forceString: true

  destination:
    server: "https://kubernetes.default.svc"
    namespace: stocks-data-sync
    